// client/todo-svelte/src/components/TodoItem.svelte
<style>
.todo-item {
  position: relative;
  padding: 1rem;
  border-width: 1px 0 0;
  border-style: solid;
  border-color: var(--mid-color);
  background-color: var(--page-bg-color);
  color: var(--page-fg-color);
  height: 3.5rem;
}
.todo-item--last {
  border-bottom-width: 1px;
}
.todo-item--complete {
  background-color: var(--page-bg-color-2);
  color: var(--page-fg-color-2);
}

.todo-item__checkbox {
  margin-right: 0.5rem;
}

.todo-item__input-text {
  padding-top: 0;
  padding-bottom: 0;
  margin-top: 0;
  margin-bottom: 0;
}

.todo-item__detail-link {
  position: absolute;
  right: 0;
  top: 0;
  width: 48px;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  text-decoration: none;
  color: var(--link-color);
}
.todo-item__detail-link:visited {
  color: var(--link-visited);
}
.todo-item__detail-link:hover {
  background-color: var(--page-bg-color-2);
}
</style>

<script>
export let todo = null;
export let isLast = false;
</script>

<li
  class="todo-item"
  class:todo-item--complete={todo.complete}
  class:todo-item--last={isLast}>
  <p>{isLast}</p>
  <!-- <input
    [(ngModel)]="isComplete"
    type="checkbox"
    class="todo-item__checkbox"
    (change)="save()"
  >
  <label
    *ngIf="!isEditing"
    (click)="isEditing = true">
    {{ data.text }}
  </label>
  <input
    type="text"
    *ngIf="isEditing"
    [(ngModel)]="data.text"
    (blur)="save()"
    (keypress)="onInputKey($event)"
    autofocus
    class="todo-item__input-text"
  >
  <a routerLink="/todos/{{ data.id }}" class="todo-item__detail-link">
    <i class="material-icons app-header__icon-link">keyboard_arrow_right</i>
  </a> -->
</li>

// client/todo-angular/src/app/todos/todo-item/todo-item.component.ts
import { Component, OnInit, Input, SimpleChanges } from '@angular/core';
import { Todo } from '../services/todos.service';

@Component({
  selector: 'app-todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.css']
})
export class TodoItemComponent implements OnInit {
  @Input() data: Todo;
  @Input() isLast: boolean;

  private privateIsComplete = false;
  public get isComplete() {
    return this.privateIsComplete;
  }
  public set isComplete(value) {
    this.privateIsComplete = value;
    this.updateContainerClass();
  }

  public isEditing = false;

  public containerClass = {
    'todo-item--last': false,
    'todo-item--complete': false,
  };

  constructor() { }

  ngOnInit() {
    this.isComplete = this.data.complete;
    this.updateContainerClass();
  }

  updateContainerClass() {
    this.containerClass = {
      'todo-item--last': this.isLast,
      'todo-item--complete': this.isComplete,
    };
  }

  onStartTextChange() {
    this.isEditing = true;
  }

  onInputKey($event) {
    if ($event.key === 'Enter') {
      $event.target.blur();
    }
  }
}

<li class="todo-item" [ngClass]="containerClass">
  <input
    [(ngModel)]="isComplete"
    type="checkbox"
    class="todo-item__checkbox"
  >
  <label
    *ngIf="!isEditing"
    (click)="isEditing = true">
    {{ data.text }}
  </label>
  <input
    type="text"
    *ngIf="isEditing"
    [(ngModel)]="data.text"
    (blur)="isEditing = false"
    (keypress)="onInputKey($event)"
    autofocus
    class="todo-item__input-text"
  >
  <a routerLink="/todos/{{ data.id }}" class="todo-item__detail-link">
    <i class="material-icons app-header__icon-link">keyboard_arrow_right</i>
  </a>
</li>
