// client/todo-angular/src/app/todos/todo-detail/todo-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, ParamMap } from '@angular/router';
import { Observable, of } from 'rxjs';
import { switchMap, catchError } from 'rxjs/operators';

import { TodosService, Todo } from '../services/todos.service';
import { HttpErrorResponse } from '@angular/common/http';

@Component({
  selector: 'app-todo-detail',
  templateUrl: './todo-detail.component.html',
  styleUrls: ['./todo-detail.component.css']
})
export class TodoDetailComponent implements OnInit {
  todo$: Observable<Todo>;
  error: HttpErrorResponse;

  constructor(
    private route: ActivatedRoute,
    private todosService: TodosService
  ) { }

  ngOnInit() {
    this.todo$ = this.route.paramMap.pipe(
      switchMap((params: ParamMap) =>
        this.todosService.getTodo(params.get('id'))),
      catchError((error: HttpErrorResponse) => {
        this.error = error;
        return of(null);
      })
    );
  }

}

<div class="todo-detail">
  <div *ngIf="!error && todo$ | async as todo">
    <label>
      <input
        type="checkbox"
        [(ngModel)]="todo.complete"
        (change)="save(todo)"
      >
      complete
    </label>
    <textarea
      [(ngModel)]="todo.text"
      placeholder="title"
      rows="2"
      class="todo-detail__textarea"
      (blur)="save(todo)"
    ></textarea>
    <textarea
      [(ngModel)]="todo.notes"
      placeholder="notes"
      rows="4"
      class="todo-detail__textarea"
      (blur)="save(todo)"
    ></textarea>
    <button (click)="delete(todo)">Delete</button>
  </div>
  <p *ngIf="error">{{ error.message }}</p>
</div>

// client/todo-svelte/src/components/TodoDetail.svelte
<style>
.todo-detail {
  padding: 0 1rem 1rem;
}
.todo-detail__textarea {
  display: block;
  width: 100%;
  margin: 1rem 0;
}
</style>

<script>
import { getContext, onDestroy } from 'svelte';
import { Todos } from 'todo-shared';
import page from 'page';

export let todo = null;

let error = null;

function saveTodo() {
  Todos.update(todo.id, todo)
    .then(data => {
      todo = data;
      error = null;
    })
    .catch(err => error = err);
}

function deleteTodo() {
  Todos.delete(todo.id)
    .then(() => page('/'))
    .catch(err => error = err);
}

const route = getContext('route');
const unsubscribeRoute = route.subscribe(context => {
  Todos.read(context.params.id)
    .then(data => {
      todo = data;
      error = null;
    })
    .catch(err => error = err);
});

onDestroy(() => {
  unsubscribeRoute();
});
</script>

<div class="app-page">
  <div class="todo-detail">
    {#if error}
    <p>{error.message}</p>
    {:else if todo}
    <div>
      <label>
        <input
          type="checkbox"
          bind:checked={todo.complete}
          on:change={saveTodo}
        >
        complete
      </label>
      <textarea
        bind:value={todo.text}
        placeholder="title"
        rows="2"
        class="todo-detail__textarea"
        on:blur={saveTodo}
      ></textarea>
      <textarea
        bind:value={todo.notes}
        placeholder="notes"
        rows="4"
        class="todo-detail__textarea"
        on:blur={saveTodo}
      ></textarea>
      <button on:click={deleteTodo}>Delete</button>
    </div>
    {/if}
  </div>

</div>
